version: '3'

# association des services
services:
  db:
    image: 'mysql:5.7'
    ports:
      - "30000:3306" # on ne veut pas l'exposer depuis l'extérieur ! Donc ce n'est pas nécessaire de mettre la partie ports.
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - dbdata:/var/lib/mysql

  app:
    build: ./app
    restart: on-failure # always
    depends_on:
      - 'db'
    links:
      - 'db'
    ports:
      - "5000:8083"

volumes:
  dbdata: