- name: Projet1
  hosts: victim

  tasks:

  - name: create docker group
    become: true
    group:
      name: docker
      state: present

  - name: add user to group 
    become: true
    user:
      name: "{{ansible_user}}"
      groups: docker
      append: true

  - name: install packages required by docker
    become: yes
    apt:
      update_cache: yes
      state: latest
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg-agent
      - software-properties-common

  - name: add docker GPG key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker apt repo
    become: yes
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: install docker
    become: yes
    apt:
      update_cache: yes
      state: latest
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  ##### setup ansible <---> docker

  - name: install python dependencies
    become: yes
    apt:
      update_cache: yes
      state: latest
      name: python3-pip

  - name: install 'Docker SDK for Python'
    #become: true               <--- DO NOT DO THIS!!!
    pip:
      name: docker

  - name: Install pip
    become: yes
    apt: name=pip state=latest
  
  - name: Install docker-compose
    become: yes
    remote_user: ubuntu
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Clone repository GitHub application Projet1
    become: yes
    git:
      repo: https://github.com/Lilowl06/tp1.git
      dest: /home/osboxes/tp1
      force: yes

#  - name : Starting docker-compose files
#    become: yes
#    shell: docker-compose up --build -d